config/routes.rb
Rails.application.routes.draw do
  resources :base_products
  devise_for :users
  devise_for :admins
  root to: "home#index"

  authenticate :admin do
    resources :products
    resources :categories
  end

  resource :cart, only: [:show, :update] do
    member do
      post :pay_with_paypal
      get  :process_paypal_payment
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/base_product.rb
class BaseProduct < ApplicationRecord
    has_many :products

    def children
        children = self.product
    end

    def children_stock
        self.product.sum(:stock)
end

app/controllers/base_products_controller.rb
class BaseProductsController < ApplicationController
  before_action :set_base_product, only: [:show, :edit, :update, :destroy]

  # GET /base_products
  # GET /base_products.json
  def index
    @base_products = BaseProduct.all
  end

  # GET /base_products/1
  # GET /base_products/1.json
  def show
  end

  # GET /base_products/new
  def new
    @base_product = BaseProduct.new
  end

  # GET /base_products/1/edit
  def edit
  end

  # POST /base_products
  # POST /base_products.json
  def create
    @base_product = BaseProduct.new(base_product_params)

    respond_to do |format|
      if @base_product.save
        format.html { redirect_to @base_product, notice: 'Base product was successfully created.' }
        format.json { render :show, status: :created, location: @base_product }
      else
        format.html { render :new }
        format.json { render json: @base_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_products/1
  # PATCH/PUT /base_products/1.json
  def update
    respond_to do |format|
      if @base_product.update(base_product_params)
        format.html { redirect_to @base_product, notice: 'Base product was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_product }
      else
        format.html { render :edit }
        format.json { render json: @base_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_products/1
  # DELETE /base_products/1.json
  def destroy
    @base_product.destroy
    respond_to do |format|
      format.html { redirect_to base_products_url, notice: 'Base product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_product
      @base_product = BaseProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def base_product_params
      params.require(:base_product).permit(:name)
    end
end

app/helpers/base_products_helper.rb
module BaseProductsHelper
end

app/views/base_products/_form.html.erb
<%= form_with(model: base_product, local: true) do |form| %>
  <% if base_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(base_product.errors.count, "error") %> prohibited this base_product from being saved:</h2>

      <ul>
      <% base_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/base_products/edit.html.erb
<h1>Editing Base Product</h1>

<%= render 'form', base_product: @base_product %>

<%= link_to 'Show', @base_product %> |
<%= link_to 'Back', base_products_path %>

app/views/base_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Base Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_products.each do |base_product| %>
      <tr>
        <td><%= base_product.name %></td>
        <td><%= link_to 'Show', base_product %></td>
        <td><%= link_to 'Edit', edit_base_product_path(base_product) %></td>
        <td><%= link_to 'Destroy', base_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base Product', new_base_product_path %>

app/views/base_products/new.html.erb
<h1>New Base Product</h1>

<%= render 'form', base_product: @base_product %>

<%= link_to 'Back', base_products_path %>

app/views/base_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @base_product.name %>
</p>

<%= link_to 'Edit', edit_base_product_path(@base_product) %> |
<%= link_to 'Back', base_products_path %>